### ISSUE TITLE
Blank screen when entering an api in parse dashboard in Firefox

### ISSUE THREAD

**Issue by markocruz** [parse-community/parse-dashboard#937]
When entering one of the applications listed after login I have a blank screen

- [ ] Parse Dashboard 1.2.0
- [ ] Parse Server 3.1.2

#### Environment Setup
Console Log
TypeError: "this.props.schema.dispatch(...) is undefined"
	value https://admin.sia.red/bundles/dashboard.bundle.js:22:731320
	co https://admin.sia.red/bundles/dashboard.bundle.js:22:55678
	Po https://admin.sia.red/bundles/dashboard.bundle.js:22:64996
	hi https://admin.sia.red/bundles/dashboard.bundle.js:22:77029
	fi https://admin.sia.red/bundles/dashboard.bundle.js:22:77336
	Ji https://admin.sia.red/bundles/dashboard.bundle.js:22:80884
	Gi https://admin.sia.red/bundles/dashboard.bundle.js:22:80396
	Ki https://admin.sia.red/bundles/dashboard.bundle.js:22:80222
	ns https://admin.sia.red/bundles/dashboard.bundle.js:22:85821
	Pn https://admin.sia.red/bundles/dashboard.bundle.js:22:31210
	s https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js:1:8500
dashboard.bundle.js:22:71864
TypeError: this.props.schema.dispatch(...) is undefined[Learn More] dashboard.bundle.js:22:731320
value
https://admin.sia.red/bundles/dashboard.bundle.js:22:731320
co
https://admin.sia.red/bundles/dashboard.bundle.js:22:55678
Po
https://admin.sia.red/bundles/dashboard.bundle.js:22:64996
hi
https://admin.sia.red/bundles/dashboard.bundle.js:22:77029
fi
https://admin.sia.red/bundles/dashboard.bundle.js:22:77336
Ji
https://admin.sia.red/bundles/dashboard.bundle.js:22:80884
Gi
https://admin.sia.red/bundles/dashboard.bundle.js:22:80396
Ki
https://admin.sia.red/bundles/dashboard.bundle.js:22:80222
ns
https://admin.sia.red/bundles/dashboard.bundle.js:22:85821
Pn
https://admin.sia.red/bundles/dashboard.bundle.js:22:31210
Pn self-hosted:1018:17 s
https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js:1:8500

uname -a
Darwin local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64

Firefox version
63.0.3 (64-bit)

**Comment by echosalik** [comment]
I have the same error in Firefox 64.0 (64-bit), but the app works in Chromium.

**Comment by dplewis** [comment]
I have verified that this is a bug. I can look into it later today

**Comment by dplewis** [comment]
I tried this against the latest code of the Parse JS SDK and this issue is fixed. Waiting for the next release.

**Comment by tpimh** [comment]
Just tried with latest version in Docker (last updated 2 hours ago) and Firefox 66. Still reproducible. Doesn't happen with 1.4.3.

**Comment by marticols** [comment]
I was using 2.0.5 with Firefox. I downgraded to 1.3.0 for getting rid of the error.
